### ISSUE TITLE
Issue: "Waiting for bitcoind to accept RPC requests..."

### ISSUE THREAD

**Issue by Ulawun** [joinmarket-webui/jam-docker#135]
Hello :-)

The ghcr.io/joinmarket-webui/jam-standalone container is running,
but doesn't do its job.
The container is "Waiting for bitcoind to accept RPC requests..." for eternity !

I'm running bitcoin core and the ghcr.io/joinmarket-webui/jam-standalone container on one computer.
Computer: Linux Mint 21.3 Virginia 64-bit
Bitcoin core: v27.1.0
Docker: 24.0.7, build: ubuntu...

This is my bitcoin core bitcoin.conf:
maxuploadtarget=1000
server=1
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=8332
rpcuser=myUser
rpcpassword=myrPassword

I tried two docker run commands:
1)
sudo docker run --rm  -it \
--add-host host.docker.internal:host-gateway \
--env JM_RPC_HOST="host.docker.internal" \
--env JM_RPC_PORT="8332" \
--env JM_RPC_USER="myUser" \
--env JM_RPC_PASSWORD="myrPassword" \
--env JM_NETWORK="regtest" \
--env APP_USER="joinmarket" \
--env APP_PASSWORD="joinmarket" \
--env ENSURE_WALLET="true" \
--env REMOVE_LOCK_FILES="true" \
--env RESTORE_DEFAULT_CONFIG="true" \
--env WAIT_FOR_BITCOIND="true" \
--volume jmdatadir:/root/.joinmarket \
--publish "8080:80" \
ghcr.io/joinmarket-webui/jam-standalone
2)
sudo docker run --rm -it \
--add-host host.docker.internal:host-gateway \
--env JM_RPC_HOST="host.docker.internal" \
--env JM_RPC_PORT="8332" \
--env JM_RPC_USER="myUser" \
--env JM_RPC_PASSWORD="myrPassword" \
--env WAIT_FOR_BITCOIND="true" \
--publish "8080:80" \
ghcr.io/joinmarket-webui/jam-standalone

Both run commands give the error:
"Waiting for bitcoind to accept RPC requests...".

On the same computer a self written NodeJS program can be run,
which is using bitcoin core RPCs properly.
So my guess is that the problem is not bitcoin core ...

Any ideas pls,
why the containewr is waiting for bitcoind for eternity ?
Thx :-)

**Comment by Ulawun** [comment]
Thanks theborakompanioni.

I tried:
sudo docker run --rm  -it \
--network host \
--env JM_RPC_HOST="host.docker.internal" \
--env JM_RPC_PORT="18443" \
--env JM_RPC_USER="myUser" \
--env JM_RPC_PASSWORD="myPassword" \
--env JM_NETWORK="regtest" \
--env APP_USER="joinmarket" \
--env APP_PASSWORD="joinmarket" \
--env ENSURE_WALLET="true" \
--env REMOVE_LOCK_FILES="true" \
--env RESTORE_DEFAULT_CONFIG="true" \
--env WAIT_FOR_BITCOIND="true" \
--volume jmdatadir:/root/.joinmarket \
--publish "8080:80" \
ghcr.io/joinmarket-webui/jam-standalone

I'm sorry to say, but the reaction is still:
"Waiting for bitcoind to accept RPC requests...".

**Comment by theborakompanioni** [comment]
> Thanks theborakompanioni.
> 
> I tried: sudo docker run --rm -it --network host --env JM_RPC_HOST="host.docker.internal" --env JM_RPC_PORT="8332" --env JM_RPC_USER="myUser" --env JM_RPC_PASSWORD="myPassword" --env JM_NETWORK="regtest" --env APP_USER="joinmarket" --env APP_PASSWORD="joinmarket" --env ENSURE_WALLET="true" --env REMOVE_LOCK_FILES="true" --env RESTORE_DEFAULT_CONFIG="true" --env WAIT_FOR_BITCOIND="true" --volume jmdatadir:/root/.joinmarket --publish "8080:80" ghcr.io/joinmarket-webui/jam-standalone
> 
> I'm sorry to say, but the reaction is still: "Waiting for bitcoind to accept RPC requests...".

Change `JM_RPC_HOST` to the actual host that runs your Bitcoin Core daemon, e.g. `localhost` or `127.0.0.1` if it runs locally. Do you try to connect to a regtest node? If that is not the case, remove `JM_NETWORK`.

**Comment by Ulawun** [comment]
Thanks a lot theborakompanioni :-)

I removed JM_NETWORK, because I'm connecting to a "normal node".
I changed JM_RPC_HOST to localhost,
but I got the same waiting for eternity !
Then I changed JM_RPC_HOST to 127.0.0.1 and
this solved my waiting issue :-)
Thanks a lot :-)
Now I can see the Jam page by using a browser,
but the run command gives me:

WARNING: Published ports are discarded when using host network mode
Remove leftover wallet lockfiles before startup...
Waiting for bitcoind to accept RPC requests...
Successfully waited for bitcoind to accept RPC requests.
Creating wallet jm_webui_default if missing...
Loading wallet jm_webui_default...
[  OK  ] tor
[  OK  ] nginx
[  OK  ] jmwalletd
[  OK  ] ob-watcher
[  OK  ] boot
dinit: Service jmwalletd process terminated with exit code 1
dinit: Service ob-watcher process terminated with exit code 1
dinit: Service jmwalletd process terminated with exit code 1
dinit: Service ob-watcher process terminated with exit code 1
dinit: Service jmwalletd process terminated with exit code 1
dinit: Service ob-watcher process terminated with exit code 1
dinit: Service jmwalletd process terminated with exit code 1
dinit: Service jmwalletd restarting too quickly; stopping.
dinit: Service jmwalletd restarting too quickly; stopping.
[STOPPD] jmwalletd
dinit: Service ob-watcher process terminated with exit code 1
dinit: Service ob-watcher restarting too quickly; stopping.
dinit: Service ob-watcher restarting too quickly; stopping.
[STOPPD] ob-watcher

Are this messages OK ?
For me the messages sound some how critical !

Any comments on this pls ?
Thanks :-)

**Comment by Ulawun** [comment]
Now my rum command looks like:

sudo docker run --rm  -it \
--network host \
--env JM_RPC_HOST="127.0.0.1" \
--env JM_RPC_PORT="8332" \
--env JM_RPC_USER="myUser" \
--env JM_RPC_PASSWORD="myPassword" \
--env APP_USER="joinmarket" \
--env APP_PASSWORD="joinmarket" \
--env ENSURE_WALLET="true" \
--env REMOVE_LOCK_FILES="true" \
--env RESTORE_DEFAULT_CONFIG="true" \
--env WAIT_FOR_BITCOIND="true" \
--volume jmdatadir:/root/.joinmarket \
--publish "8080:80" \
ghcr.io/joinmarket-webui/jam-standalone

**Comment by theborakompanioni** [comment]
Okay, nice, progress! Now you can at least talk to Bitcoin Core.
Next step is to find out why they do not like each other at the moment.
As this is a manual setup, have you completed the preliminary steps: e.g.
- make sure you have [`deprecatedrpc=create_bdb` configured](https://jamdocs.org/FAQ/#jam-doesnt-work-anymore-after-updating-bitcoin-core-to-v260) 
- [setting up a wallet](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/USAGE.md#setting-core-wallet) (should be done for you and handled by the docker image, if I am not mistaken)

**Comment by Ulawun** [comment]
Thanks a lot theborakompanioni :-)

With this link:
"make sure you have [deprecatedrpc=create_bdb configured](https://jamdocs.org/FAQ/#jam-doesnt-work-anymore-after-updating-bitcoin-core-to-v260)"
you solved my issue :-)
Now I have jam-docker running and I am very, very happy :-)

Thanks, thanks, thanks

**Comment by theborakompanioni** [comment]
> Thanks a lot theborakompanioni :-)
> 
> With this link: "make sure you have [deprecatedrpc=create_bdb configured](https://jamdocs.org/FAQ/#jam-doesnt-work-anymore-after-updating-bitcoin-core-to-v260)" you solved my issue :-) Now I have jam-docker running and I am very, very happy :-)
> 
> Thanks, thanks, thanks

Hey @Ulawun! Glad to hear that. Please keep the issues coming if you encounter any problems or bug. Feedback is always welcome and highly appreciated. :pray: 

I will close the issue now.
