### ISSUE TITLE
Question: How to change settings in joinmarket.cfg ?

### ISSUE THREAD

**Issue by Ulawun** [joinmarket-webui/jam-docker#136]
Hello :-)

The ghcr.io/joinmarket-webui/jam-standalone container is running and
I can access it via firefox :-)
Now I want to be maker and set my fees to zero.

I found out, that I have to add/change the joinmarket.cfg file
with the line "ordertype = absoffer".
Is this correct ?

I created a joinmarket.cfg file on the server
with the content: "ordertype = absoffer".
Then I started docker with this parameter
"--env RESTORE_DEFAULT_CONFIG="/path/to/my/folder/joinmarket.cfg".
When I then start docker and click "earn",
it is shown, that my fee is greater than zero !
What do I have to do ?

Any ideas pls ?
Thx :-)

**Comment by theborakompanioni** [comment]
> Hello :-)
> 
> The ghcr.io/joinmarket-webui/jam-standalone container is running and I can access it via firefox :-)
Great! :-)

> Now I want to be maker and set my fees to zero.
:100: :pray: 

> I found out, that I have to add/change the joinmarket.cfg file with the line "ordertype = absoffer". Is this correct ?

If you are using Jam, you can select that open on the Earn page! See the "Offer options" dropdown!
https://jamdocs.org/interface/03-earn/#offer-options

> 
> I created a joinmarket.cfg file on the server with the content: "ordertype = absoffer". Then I started docker with this parameter "--env RESTORE_DEFAULT_CONFIG="/path/to/my/folder/joinmarket.cfg". When I then start docker and click "earn", it is shown, that my fee is greater than zero ! What do I have to do ?

See above. I think this is easier for what you want to achieve.

`RESTORE_DEFAULT_CONFIG`  is a boolean flag and must be disabled, if you want to bring a completely custom config to the image.  However, I think this not necessary in this case.

> Any ideas pls ? Thx :-)

Let us know, if it worked. :pray:

**Comment by Ulawun** [comment]
Thanks a lot theborakompanioni :-)

I first tried the "Offer options" dropdown
to set my maker fees to zero,
see attached picture "1":
![1](https://github.com/user-attachments/assets/85fbc4e7-cba7-45db-8f07-b24eb3424da7)

When I do this,
the earn page doesn't show any offers,
see attached picture "2":
![2](https://github.com/user-attachments/assets/62aa408a-be71-4929-8418-a650fae1610f)

For me it looks like,
that joinmarket doesn't accept the maker fee to be zero !
Also on the "orderbook" page
there is no maker offer with zero fee !

When I set my maker fees to 1 sats,
my maker offer is working !

I would like to offer a zero fee mix,
because then I would have better chances to be mixed ...

Do you know a way to offer a maker fee of zero ?

**Comment by theborakompanioni** [comment]
> Do you know a way to offer a maker fee of zero ?

Yes, I think [this has been fixed](https://github.com/joinmarket-webui/jam/issues/726) and works in the current version (v0.3.0). Update Jam and creating an "absolute offer" with 0 sats should be possible.

**Comment by theborakompanioni** [comment]
> > Do you know a way to offer a maker fee of zero ?
> 
> Yes, I think [this has been fixed](https://github.com/joinmarket-webui/jam/issues/726) and works in the current version (v0.3.0). Update Jam and creating an "absolute offer" with 0 sats should be possible.
> 
> Edit: Docker image [`ghcr.io/joinmarket-webui/jam-standalone:v0.3.0-clientserver-v0.9.11`](https://github.com/joinmarket-webui/jam-docker/pkgs/container/jam-standalone/282906699?tag=v0.3.0-clientserver-v0.9.11).

By the way, thanks for pointing this out. A relative offer with 0% leads to a crash of the backend, so this should be prevented. :pray:

**Comment by Ulawun** [comment]
Thanks a lot theborakompanioni :-)
I will upgrade to v0.3.0, when my newest issue is fixed: https://github.com/joinmarket-webui/jam-docker/issues/137
Thx :-)

**Comment by Ulawun** [comment]
Thanks again :-)
Yes, can be closed.
I will try to close threads in the future ...
