### ISSUE TITLE
A maker mix is getting stuck !

### ISSUE THREAD

**Issue by Ulawun** [joinmarket-webui/jam-docker#137]
Hello Group :-)

With the help of this group I successfully got jam-docker to run :-)
Now I'm running v0.2.0 and I know, that there's v0.3.0 available.
I will upgrade, when my actual issue is fixed !

10 days ago I started my first (and last) mix with JoinMarket as a maker.
Before starting the maker mix I had BTC in Apricot wallet.
After starting the maker mix jam is showing
that there is BTC in Apricot wallet and Blueberry wallet.
Looks like a mix :-)
The "Earnings report" page said "connected".

When I have a look to the Apricot address with mempool.space and sparrow,
it looks like that there is the original amount of BTC in Apricot wallet and nothing is in mempool.

Ca. 8 days ago I stopped mixing via jam.
Till now jam is showing BTC in Apricot and Blueberry wallet.
Looks like nothing is happening for the last 8 days !
I don't know really the status of my mix !

When I try to send BTC from Apricot or from Blueberry wallet via Jam,
I get attached error !

How can I find out the status of my mix ?
Is there a way to really stop maker mixing ?
What is best practice to get jam to run again ?
Do I take any risks, when I stop the jam-docker v0.2.0 and
try to continue with jam-docker v0.3.0 ?

Any ideas pls ?
Thx :-)

![Bildschirmfoto zu 2024-10-24 18-21-42](https://github.com/user-attachments/assets/64c19819-7064-4f21-8dbe-17895f2c3a96)

**Comment by theborakompanioni** [comment]
> Hello Group :-)

> Any ideas pls ? Thx :-)

I can try. 

> How can I find out the status of my mix ?

Jam/JM reporting in this regard is still underwhelming. Hopefully https://github.com/joinmarket-webui/jam/issues/515 can be implemented in the future. So, currently, you only know if a transactions has been included in the chain by the number of confirmations of your UTXOs, or by looking at the chain with other external tools (e.g. your self-hosted block explorer).

There are [reports that maker processes sometimes get stuck](https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1588). In this case, try locking/unlocking the wallet first.

> Is there a way to really stop maker mixing ?

Yes, by stopping the maker process or by locking your wallet.

> What is best practice to get jam to run again ?

Lock and unlock your wallet. If that does not work, restart your node. If that also does not change anything, rescan the chain for your funds.

> Do I take any risks, when I stop the jam-docker v0.2.0 and try to continue with jam-docker v0.3.0 ?

Other than that you might have to re-import your wallet (and wait for the synchronization to finish), there should be no risk. I cannot stress enough: Make sure you have written down your seed phrase (preferably hammered in steel).

> When I try to send BTC from Apricot or from Blueberry wallet via Jam, I get attached error !

The error means, that you have to wait for the UTXO to have five or more confirmations before attempting another collaborative transaction.

- Make sure you have written down your seed phrase.
- Lock/unlock wallet.
- Restart node.
- Upgrade to v0.3.0
- Re-import your wallet.

**Comment by Ulawun** [comment]
Thanks a lot theborakompanioni :-)

I upgraded to v0.3.0.
I found my BTC there.
I could set the maker fees to zero.
Now I'm offering mixes as a maker again.
I'm curious, if mixes will happen ...
I close this threat as "completed".

Happy mixing :-)

**Comment by theborakompanioni** [comment]
Happy it worked out for you.

> Happy mixing :-)

Jam is for creating collaborative transaction.
